files: 
  - name: "pin_mapping.pin"
    file_type: pin
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
  - name: "UP_COUNTER.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
hooks: 
  pre_build: 
    []
  post_build: 
    []
  pre_run: 
    []
  post_run: 
    []
watchers: 
  []
name: raptor_counter_vhdl
tool_options: 
  ghdl: 
    name: ghdl
    installation_path: ""
    config: 
      installation_path: ""
      waveform: vcd
      analyze_options: 
        []
      run_options: 
        []
toplevel: "UP_COUNTER.vhd"