toplevel: "half_adder_lookup_tb"
name: project_modelsim
files: 
  - name: "half_adder_tb.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
  - name: "half_adder.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
tool_options: 
  modelsim: 
    installation_path: ""
    vlog_options: ""
    vsim_options: ""