toplevel: control_logic
name: state_machine_examples
files: 
  ##########################################################
  # Verilog
  ##########################################################
  - name: "fsm_0.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""

  - name: "fsm_1.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""

  ##########################################################
  # VHDL
  ##########################################################
  - name: "fsm_0.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""

  - name: "fsm_1.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""

  - name: "fsm_2.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""

  - name: "fsm_3.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""

  - name: "fsm_4.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""

  - name: "fsm_5.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""

  - name: "fsm_6.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""

tool_options: 
  ghdl: 
    installation_path: ""
    waveform: vcd
    analyze_options: 
      - "--ieee=synopsys"
    run_options: 
      - ""
    linter_options: 
      - ""