toplevel: evaluate_example
name: editor_example
files: 
  #############################################3
  # Evaluate
  #############################################3
  - name: "evaluate.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
    include_path: ""
    logical_name: ""
  - name: "evaluate.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
tool_options: 
  ghdl: 
    installation_path: ""
    waveform: vcd
    analyze_options: 
      - "--ieee=synopsys"
    run_options: 
      - ""
    linter_options: 
      - ""