toplevel: ""
name: project_xsim
files: 
  - name: "half_adder_tb.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
  - name: "half_adder.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
tool_options: 
  xsim: 
    installation_path: ""
    xelab_options: ""
    xsim_options: ""