files: 
  - name: "constraints.sdc"
    file_type: sdc
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
  - name: "counter.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
hooks: 
  pre_build: 
    []
  post_build: 
    []
  pre_run: 
    []
  post_run: 
    []
watchers: 
  []
name: raptor_counter
tool_options: 
  ghdl: 
    name: ghdl
    installation_path: ""
    config: 
      installation_path: ""
      waveform: vcd
      analyze_options: 
        []
      run_options: 
        []
toplevel: "counter.v"