toplevel: blinky_zcu106
name: project_vivado
files: 
  - name: "blinky_zcu106.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
  - name: "blinky.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
  - name: "blinky.xdc"
    file_type: XDC
    is_include_file: false
    include_path: ""
    logical_name: ""
tool_options: 
  vivado: 
    installation_path: ""
    part: XC7Z010
    pnr: vivado