toplevel: ""
name: project_ghdl
files: 
  - name: "half_adder_tb.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
  - name: "half_adder.vhd"
    file_type: "vhdlSource-2008"
    is_include_file: false
tool_options: 
  ghdl: 
    installation_path: ""
    waveform: ""
    analyze_options: "-fexplicit\x2C--no-vital-checks\x2C-frelaxed-rules"
    run_options: ""