name: documenter_ci

on:
  push:
    branches:
      - main

jobs:
  teroshdl-doc:
    name: '📓 Docs'
    runs-on: ubuntu-latest
    container:
      image: docker://terostech/colibri:latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
    - name: 'doc_gen'
      run: |
        cd documenter/documenter_ci
        teroshdl-hdl-documenter -i teros_project.yml -o html --dep --fsm -s all -c all -p all --symbol_vhdl ! --outpath built_doc 
        apt install -y rsync

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: documenter/documenter_ci/built_doc # The folder the action should deploy.