name: documenter_ci

on:
  push:
    branches:
      - master

jobs:
  teroshdl-doc:
    name: '📓 Docs'
    runs-on: ubuntu-latest
    container:
      image: docker://terostech/colibri:latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
    - name: 'doc_gen'
      run: |
        cd project_manager/documenter_CI
        teroshdl-hdl-documenter -f teros_project.trs -o html
        apt install -y rsync

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: project_manager/documenter_CI/built_doc # The folder the action should deploy.