name: Test_examples

on: [push]

jobs:
  test-suites:
    runs-on: ubuntu-18.04
    container:
      image: docker://terostech/multi-simulator:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          cd project_manager/vunit
          python3 run.py lib.tb_minimal.all
          cd ..
          cd cocotb
          make
          